<template>
	<div class="pairing-overlay">
		<div class="pairing-card">
			<div class="pairing-logo">nexterm</div>
			<h2 class="pairing-title">Authentication Required</h2>
			<p class="pairing-subtitle">
				Enter the 6-digit pairing code shown on the host machine, or the code
				generated by an already-authenticated client.
			</p>

			<form class="pairing-form" @submit.prevent="handleSubmit">
				<div class="code-input-row">
					<input
						ref="codeInputRef"
						v-model="code"
						class="code-input"
						type="text"
						inputmode="numeric"
						maxlength="6"
						pattern="[0-9]{6}"
						placeholder="000000"
						autocomplete="one-time-code"
						:disabled="loading"
						@input="onInput"
					/>
				</div>

				<p v-if="errorMsg" class="pairing-error" role="alert">{{ errorMsg }}</p>
				<p v-if="successMsg" class="pairing-success" role="status">{{ successMsg }}</p>

				<button type="submit" class="pairing-btn" :disabled="loading || code.length !== 6">
					<span v-if="loading" class="spinner" aria-hidden="true" />
					{{ loading ? "Verifying…" : "Connect" }}
				</button>
			</form>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useAuthStore } from "../stores/auth.js";
import { useSessionStore } from "../stores/session.js";

const emit = defineEmits<{
	authenticated: [];
}>();

const authStore = useAuthStore();
const sessionStore = useSessionStore();

const code = ref("");
const loading = ref(false);
const errorMsg = ref<string | null>(null);
const successMsg = ref<string | null>(null);
const codeInputRef = ref<HTMLInputElement | null>(null);

onMounted(() => {
	codeInputRef.value?.focus();
});

/** Strip non-digits and cap at 6 chars. */
function onInput(): void {
	code.value = code.value.replace(/\D/g, "").slice(0, 6);
}

async function handleSubmit(): Promise<void> {
	if (code.value.length !== 6) return;

	loading.value = true;
	errorMsg.value = null;
	successMsg.value = null;

	try {
		const res = await fetch("/api/pair/verify", {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({ code: code.value }),
		});

		if (!res.ok) {
			const body = (await res.json().catch(() => ({ message: "Verification failed" }))) as {
				message?: string;
			};
			throw new Error(body.message ?? `HTTP ${res.status}`);
		}

		const data = (await res.json()) as { token: string };
		authStore.setToken(data.token);
		successMsg.value = "Authenticated! Connecting…";

		// Re-initialise the WS connection with the new token.
		// The session store will send AUTH on connect.
		sessionStore.disconnect();
		await sessionStore.connect();

		emit("authenticated");
	} catch (err) {
		errorMsg.value = err instanceof Error ? err.message : String(err);
		code.value = "";
		codeInputRef.value?.focus();
	} finally {
		loading.value = false;
	}
}
</script>

<style scoped>
.pairing-overlay {
	position: fixed;
	inset: 0;
	background: rgba(var(--nt-bg-rgb), 0.92);
	backdrop-filter: blur(6px);
	display: flex;
	align-items: center;
	justify-content: center;
	z-index: 1000;
}

.pairing-card {
	background: var(--nt-bg);
	border: 1px solid var(--nt-border);
	border-radius: 12px;
	padding: 40px 48px;
	width: 380px;
	max-width: calc(100vw - 32px);
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 0;
	box-shadow: var(--nt-shadow);
}

.pairing-logo {
	font-size: 20px;
	font-weight: 700;
	color: var(--nt-accent);
	letter-spacing: 0.04em;
	margin-bottom: 20px;
}

.pairing-title {
	margin: 0 0 8px;
	font-size: 18px;
	font-weight: 600;
	color: var(--nt-fg);
	text-align: center;
}

.pairing-subtitle {
	margin: 0 0 28px;
	font-size: 12px;
	color: var(--nt-text-muted);
	text-align: center;
	line-height: 1.6;
}

.pairing-form {
	width: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 16px;
}

.code-input-row {
	width: 100%;
	display: flex;
	justify-content: center;
}

.code-input {
	width: 180px;
	height: 56px;
	text-align: center;
	font-size: 28px;
	font-weight: 700;
	letter-spacing: 0.25em;
	font-family: "Cascadia Code", "Fira Code", monospace;
	background: var(--nt-tab-bar);
	border: 1px solid var(--nt-border);
	border-radius: 8px;
	color: var(--nt-fg);
	outline: none;
	transition: border-color 0.15s;
}

.code-input:focus {
	border-color: var(--nt-accent);
}

.code-input:disabled {
	opacity: 0.5;
}

.pairing-error {
	margin: 0;
	font-size: 12px;
	color: var(--nt-badge);
	text-align: center;
}

.pairing-success {
	margin: 0;
	font-size: 12px;
	color: var(--nt-green);
	text-align: center;
}

.pairing-btn {
	width: 100%;
	height: 40px;
	background: var(--nt-accent);
	color: var(--nt-bg);
	font-size: 14px;
	font-weight: 600;
	border: none;
	border-radius: 8px;
	cursor: pointer;
	transition: background 0.15s, opacity 0.15s;
	display: flex;
	align-items: center;
	justify-content: center;
	gap: 8px;
}

.pairing-btn:hover:not(:disabled) {
	filter: brightness(1.15);
}

.pairing-btn:disabled {
	opacity: 0.45;
	cursor: not-allowed;
}

.spinner {
	width: 14px;
	height: 14px;
	border: 2px solid rgba(var(--nt-bg-rgb), 0.3);
	border-top-color: var(--nt-bg);
	border-radius: 50%;
	animation: spin 0.7s linear infinite;
	flex-shrink: 0;
}

@keyframes spin {
	to {
		transform: rotate(360deg);
	}
}
</style>
